Use a newer version of the JRuby uberjar
Version 1.6.7.2 bundled an unshaded-but-incompatible (with Bio-Formats)
version of joda time. The new version works.

Upon cursory inspection, the JAR may still not be shading joda time, but
if not, it must be a newer version that works with Bio-Formats because
the NoSuchMethodErrors are gone and things work again.